### ISSUE TITLE
Boss fails to create a cement app

### ISSUE THREAD

**Issue by dkamit** [datafolklabs/boss#32]
Hi

I tried to create cement app using the Boss template.
As per cement app documentation from the [link](http://builtoncement.com/2.10/dev/boss_templates.html) I executed

`boss create ./myapp -t boss:cement-app`

fails with the error as below
`BossTemplateError: No supported config found.`

Your help is much-appreciated thanks

**Comment by tumbak** [comment]
I had the same issue, solved it by installing boss into a venv and created the following as boss.yml in the same directory as the venv.

```yaml
variables:
    version: Version
    module: Python Module Name
    project: Project Name
    description: Project Description
    creator: Project Creator
    email: Project Creator Email
    license: License
    url: Project Url

external_files:
    .gitignore: https://raw.github.com/github/gitignore/master/Python.gitignore
    LICENSE: https://raw.github.com/datafolklabs/license/master/@license@
```
